---
title: "SVM"
output:
  html_document:
    df_print: paged
---
```{r}
set.seed(120)
```
```{r}
x <-  matrix(rnorm(60), 20, 2)
x
```
```{r}
y <-  factor(rep(c(-1, 1), c(10, 10)))
y
```
```{r}
x[y == 1] <- x[y == 1] + 3
x
```

```{r}
newdata <- data.frame(x,y)
head(newdata)
```
```{r}
colnames(newdata) <- c("Calories", "Total.Fat", "Cholesterol")
newdata
```
```{r}
plot(newdata$Calories,newdata$Total.Fat, col = ifelse(y=="1", "blue", "red"), pch = 19)
```
```{r}
library(e1071)
modelSVM1 <- svm(Cholesterol ~ ., data = newdata, kernel = "linear")
print(modelSVM1)
```
```{r}
plot(modelSVM1, newdata)
```
```{r}
library(caret)
set.seed(1)
```
```{r}
trainIndex <- createDataPartition(newdata$Cholesterol, p = 0.6)$Resample1
trainingSet <- newdata[trainIndex, ]
testingSet <- newdata[-trainIndex, ]
trainingSet
```
```{r}
testingSet
```
```{r}
summary(newdata)
```

```{r}
train_control <- trainControl(method="cv", number=20)
modelNB <- train(Cholesterol ~ Calories + Total.Fat, method = "nb", trControl = train_control, data = newdata)
modelNB$resample
```
```{r}
confusionMatrix(modelNB)
```

```{r}
train_control <- trainControl(method="repeatedcv", number=20, repeats=100)
modelNB <- train(Cholesterol ~ Calories + Total.Fat, method = "nb", trControl = train_control, data = newdata)
modelNB$resample
```
```{r}
confusionMatrix(modelNB)
```
```{r}
train_control <- trainControl(method="LOOCV")
modelNB <- train(Cholesterol ~ Calories + Total.Fat, method = "nb", trControl = train_control, data = newdata)
modelNB$results
```